/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.talentbridge.hirewise.job_posting_system.ui;

import com.talentbridge.hirewise.custom_components.CCOrganizationElement;
import com.talentbridge.hirewise.custom_components.CCScrollBar;
import com.talentbridge.hirewise.custom_components.CCSkillElement;
import com.talentbridge.hirewise.job_posting_system.dao.ApplicantDAO;
import com.talentbridge.hirewise.job_posting_system.dao.CVDAO;
import com.talentbridge.hirewise.job_posting_system.dao.SkillDAO;
import com.talentbridge.hirewise.job_posting_system.model.Applicant;
import com.talentbridge.hirewise.job_posting_system.model.CV;
import com.talentbridge.hirewise.job_posting_system.model.Organization;
import com.talentbridge.hirewise.job_posting_system.model.Skill;
import com.talentbridge.hirewise.job_posting_system.service.ApplicantService;
import com.talentbridge.hirewise.job_posting_system.service.ApplicationService;
import com.talentbridge.hirewise.job_posting_system.service.OrganizationService;
import com.talentbridge.hirewise.job_posting_system.service.SkillService;
import com.talentbridge.hirewise.personnel_system.core.IPage;
import com.talentbridge.hirewise.personnel_system.ui.MainFrame;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author Lenovo
 */
public class CVPanel extends javax.swing.JPanel implements IPage {

    /**
     * Creates new form CVPanel
     */
    ApplicantService applicantService = new ApplicantService();
    public CVPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        AboutTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        ExternalSourceTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UpdateButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        SkillAddButton = new javax.swing.JButton();
        SkillNameTextField = new javax.swing.JTextField();
        SkillAreaTextField = new javax.swing.JTextField();
        OrganizationAddLabel = new javax.swing.JButton();

        jLabel1.setText("Title");

        jLabel2.setText("About");

        jLabel3.setText("E-Mail");

        jLabel4.setText("Phone");

        jLabel5.setText("External Source");

        jLabel6.setText("Skills");

        jLabel7.setText("Organizations");

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("FirstName");

        jLabel9.setText("LastName");

        SkillAddButton.setText("Add");
        SkillAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkillAddButtonActionPerformed(evt);
            }
        });

        OrganizationAddLabel.setText("Add");
        OrganizationAddLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganizationAddLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ExternalSourceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitleTextField)
                            .addComponent(AboutTextField)
                            .addComponent(EmailTextField)
                            .addComponent(PhoneTextField)
                            .addComponent(FirstNameTextField)
                            .addComponent(LastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SkillAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SkillNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SkillAddButton)
                                    .addComponent(OrganizationAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SkillNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SkillAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SkillAddButton)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AboutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ExternalSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OrganizationAddLabel)
                        .addGap(92, 92, 92)))
                .addGap(18, 18, 18)
                .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
    
    if(applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()) == null){
    try {
        
        
        CV cv = new CV();
        cv.setTitle(TitleTextField.getText());
        cv.setAbout(AboutTextField.getText());
        cv.setEmail(EmailTextField.getText());
        cv.setPhone(PhoneTextField.getText());
        cv.setExternalSource(ExternalSourceTextField.getText());

       
        CVDAO cvDAO = new CVDAO();
        cvDAO.insert(cv);
        cv.setCvId(cv.getCvId()); // Veritabanından dönen ID'yi ata
        System.out.println("CV created successfully with ID: " + cv.getCvId());
        
      
        Applicant applicant = new Applicant();
        applicant.setUserId(MainFrame.instance.getAccount().getUserId());
        applicant.setCvId(cv.getCvId());
        applicant.setFirstName(FirstNameTextField.getText());
        applicant.setLastName(LastNameTextField.getText());
        applicant.setEmail(EmailTextField.getText());
        applicant.setPhone((PhoneTextField.getText()));
        
      
        ApplicantDAO applicantDAO = new ApplicantDAO(); 
        applicantDAO.insert(applicant);
        applicant.setApplicantId(applicant.getApplicantId());
       

        System.out.println("Applicant created successfully with ID: " + applicant.getApplicantId());

      

    } catch (Exception e) {
        System.out.println("Error occurred while creating CV: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    else{
         CV cv = applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()).getCV();  
         
        cv.setTitle(TitleTextField.getText());
        cv.setAbout(AboutTextField.getText());
        cv.setEmail(EmailTextField.getText());
        cv.setPhone(PhoneTextField.getText());
        cv.setExternalSource(ExternalSourceTextField.getText());
        
        CVDAO cvdao= new CVDAO();
        cvdao.update(cv);
        
        System.out.println("CV succesfully updated");
         
            }
    }
    
    private void SkillAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkillAddButtonActionPerformed
        
         String skillName = SkillNameTextField.getText();
         String skillArea = SkillAreaTextField.getText();
               
                // Skill objesi oluştur ve DAO'yu çağır
                Skill skill = new Skill();
                skill.setSkillName(skillName);
                skill.setSkillArea(skillArea);
                skill.setCvId(applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()).getCV().getCvId());

                SkillDAO skillDAO = new SkillDAO();
                skillDAO.insert(skill);

                System.out.println("Skill added successfully.");
                // TextField'ları temizle
                SkillNameTextField.setText("");
                SkillAreaTextField.setText("");
    }//GEN-LAST:event_SkillAddButtonActionPerformed

    private void OrganizationAddLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganizationAddLabelActionPerformed
         MainFrame.instance.setPage(MainFrame.instance.getOrganizationAddPage());
    }//GEN-LAST:event_OrganizationAddLabelActionPerformed
    
    
    
    
    
    
    
    public List<Skill> getSkills() {
        SkillService skillService = new SkillService(); 
            return skillService.getAllSkills(); 
        
    }
    private void createSkillList() {
        List<Skill> skills = getSkills();

        JPanel resultContainer = new JPanel();
        resultContainer.setSize(400, 100 * skills.size());
        GridLayout gridLayout = new GridLayout(skills.size(), 1);
        gridLayout.setVgap(5);
        resultContainer.setLayout(gridLayout);

        for (Skill skill : skills) {
            CCSkillElement skillElement = new CCSkillElement(skill);
            skillElement.setSize(200, 50);
            resultContainer.add(skillElement);
        }

        jScrollPane1.setViewportView(resultContainer);

        jScrollPane1.setVerticalScrollBar(new CCScrollBar());
        CCScrollBar sp = new CCScrollBar();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        jScrollPane1.setHorizontalScrollBar(sp);
    }
    
    public List<Organization> getOrganizations(){
        OrganizationService organizationService = new OrganizationService();
        return organizationService.getAllOrganizations();
    }
    private void createOrganizationList(){
        List<Organization> organizations = getOrganizations();
        
         JPanel resultContainer = new JPanel();
        resultContainer.setSize(400, 100 * organizations.size());
        GridLayout gridLayout = new GridLayout(organizations.size(), 1);
        gridLayout.setVgap(5);
        resultContainer.setLayout(gridLayout);

        for (Organization organization : organizations) {
            CCOrganizationElement organizationElement = new CCOrganizationElement(organization);
            organizationElement.setSize(200, 50);
            resultContainer.add(organizationElement);
        }

        jScrollPane2.setViewportView(resultContainer);

        jScrollPane2.setVerticalScrollBar(new CCScrollBar());
        CCScrollBar sp = new CCScrollBar();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        jScrollPane2.setHorizontalScrollBar(sp);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AboutTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField ExternalSourceTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JButton OrganizationAddLabel;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton SkillAddButton;
    private javax.swing.JTextField SkillAreaTextField;
    private javax.swing.JTextField SkillNameTextField;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onPageSetted() {
        createOrganizationList();
        createSkillList();
        if(applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()) == null){
            FirstNameTextField.setText("Your FirstName");
            LastNameTextField.setText("Your LastName");
            TitleTextField.setText("Your Title");
            AboutTextField.setText("Tell Us About Yourself");
            EmailTextField.setText("Your E-Mail");
            PhoneTextField.setText("Your Phone Number");
            ExternalSourceTextField.setText("Your External Sources");
        }
        else{
        var cv = applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()).getCV();
        FirstNameTextField.setText(applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()).getFirstName());
        LastNameTextField.setText(applicantService.getApplicantByUserId(MainFrame.instance.getAccount().getUserId()).getLastName());
        TitleTextField.setText(cv.getTitle());
        AboutTextField.setText(cv.getAbout());
        EmailTextField.setText(cv.getEmail());
        PhoneTextField.setText(cv.getPhone());
        ExternalSourceTextField.setText(cv.getExternalSource());
        }
    }
}
