/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.talentbridge.hirewise.job_posting_system.ui;

import com.talentbridge.hirewise.custom_components.CCHRJobPostElement;
import com.talentbridge.hirewise.custom_components.CCJobPostElement;
import com.talentbridge.hirewise.custom_components.CCScrollBar;
import com.talentbridge.hirewise.job_posting_system.model.JobPosting;
import com.talentbridge.hirewise.job_posting_system.service.JobPostingService;
import com.talentbridge.hirewise.personnel_system.core.IPage;
import com.talentbridge.hirewise.personnel_system.ui.MainFrame;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author Lenovo
 */
public class HRJobPostsPanel extends javax.swing.JPanel implements IPage{

    /**
     * Creates new form HRJobPostsPanel
     */
    public HRJobPostsPanel() {
        initComponents();

        SearchButton.addActionListener(evt -> onSearch());
        SearchField.addActionListener(evt -> onSearch());
        StatusComboBox.addActionListener(evt -> onSearch());
    }

    public List<JobPosting> getJobPosts(String titleFilter, String statusFilter) {
        JobPostingService jobPostService = new JobPostingService();

        if ((titleFilter == null || titleFilter.isEmpty()) && (statusFilter == null || statusFilter.isEmpty())) {
            return jobPostService.getAllJobPostings(); // Tüm kayıtlar
        } else {
            return jobPostService.filterJobPostings(titleFilter, statusFilter); // Filtrelenmiş kayıtlar
        }
    }

    private void createJobPostsList(String titleFilter, String statusFilter) {
        List<JobPosting> jobPosts = getJobPosts(titleFilter, statusFilter);

        JPanel resultContainer = new JPanel();
        resultContainer.setSize(570, 100 * jobPosts.size());
        GridLayout gridLayout = new GridLayout(jobPosts.size(), 1);
        gridLayout.setVgap(5);
        resultContainer.setLayout(gridLayout);

        for (JobPosting jobPost : jobPosts) {
            CCHRJobPostElement userListElement = new CCHRJobPostElement(jobPost);
            userListElement.setSize(550, 100);
            resultContainer.add(userListElement);
        }

        jScrollPane1.setViewportView(resultContainer);

        jScrollPane1.setVerticalScrollBar(new CCScrollBar());
        CCScrollBar sp = new CCScrollBar();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        jScrollPane1.setHorizontalScrollBar(sp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        StatusComboBox = new javax.swing.JComboBox<>();
        CreateButton = new javax.swing.JButton();

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Open", "Closed" }));

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(SearchButton)
                        .addGap(30, 30, 30)
                        .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(418, 418, 418)
                            .addComponent(CreateButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(CreateButton)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
       MainFrame.instance.setPage(MainFrame.instance.getHRJobPublishPage());
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void onSearch() {
        String filterText = SearchField.getText().trim();
        String statusFilter = (String) StatusComboBox.getSelectedItem();

        // "All" seçiliyse filtreleme yapma
        if ("All".equals(statusFilter)) {
            statusFilter = null;
        }

        createJobPostsList(filterText, statusFilter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onPageSetted() {
        createJobPostsList(null,null);
    }
}
