/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.talentbridge.hirewise.job_posting_system.ui;
import com.talentbridge.hirewise.job_posting_system.model.JobPosting;
import com.talentbridge.hirewise.job_posting_system.service.JobPostingService;

import javax.swing.*;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
/**
 *
 * @author Lenovo
 */
public class HRJobPublishPanel extends javax.swing.JPanel {
    private JobPostingService jobPostingService;
    /**
     * Creates new form JobPublishPanel
     */
    public HRJobPublishPanel() {
        jobPostingService = new JobPostingService(); // Service başlat
        initComponents(); // GUI Builder tarafından oluşturulan kod
        additionalInit(); // Ek işlevsellik ve bileşenler burada tanımlanır
    }
private void additionalInit() {
        // CreateButton için ActionListener ekle
        CreateButton.addActionListener(evt -> handleCreateButtonAction());
    }

    /**
     * "Create" butonu işlevselliği
     */
    private void handleCreateButtonAction() {
        // Kullanıcıdan alınan veriler
        String position = PositionTextField.getText().trim();
        String description = DescriptionTextField.getText().trim();
        String startDateStr = StartDateTextField.getText().trim();
        String status = StatusTextField.getText().trim();

        // Doğrulama
        if (position.isEmpty() || description.isEmpty() || startDateStr.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Tarih doğrulama
            LocalDate startDate = LocalDate.parse(startDateStr);

            // JobPosting nesnesi oluştur
            JobPosting jobPosting = new JobPosting();
            jobPosting.setPositionId(Integer.parseInt(position)); // Pozisyon ID'si numerik olmalı
            jobPosting.setDescription(description);
            jobPosting.setPostingDate(Date.valueOf(startDate));
            jobPosting.setStatus(status);

            // Veritabanına kaydet
            jobPostingService.addJobPosting(jobPosting);

            JOptionPane.showMessageDialog(this, "Job posting created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Alanları temizle
            clearFields();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Position ID must be a number!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use yyyy-MM-dd.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error creating job posting: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Alanları temizler
     */
    private void clearFields() {
        PositionTextField.setText("");
        DescriptionTextField.setText("");
        StartDateTextField.setText("");
        StatusTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cCRoundedButton1 = new com.talentbridge.hirewise.custom_components.CCRoundedButton();
        cCRoundedButton2 = new com.talentbridge.hirewise.custom_components.CCRoundedButton();
        cCRoundedButton3 = new com.talentbridge.hirewise.custom_components.CCRoundedButton();
        jLabel1 = new javax.swing.JLabel();
        PositionTextField = new javax.swing.JTextField();
        DescriptionTextField = new javax.swing.JTextField();
        cCPaintedCircle1 = new com.talentbridge.hirewise.custom_components.CCPaintedCircle();
        StartDateTextField = new javax.swing.JTextField();
        cCPaintedCircle2 = new com.talentbridge.hirewise.custom_components.CCPaintedCircle();
        StatusTextField = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Publish Job");

        PositionTextField.setText("jTextField1");

        DescriptionTextField.setText("jTextField1");

        javax.swing.GroupLayout cCPaintedCircle1Layout = new javax.swing.GroupLayout(cCPaintedCircle1);
        cCPaintedCircle1.setLayout(cCPaintedCircle1Layout);
        cCPaintedCircle1Layout.setHorizontalGroup(
            cCPaintedCircle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        cCPaintedCircle1Layout.setVerticalGroup(
            cCPaintedCircle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        StartDateTextField.setText("jTextField1");

        javax.swing.GroupLayout cCPaintedCircle2Layout = new javax.swing.GroupLayout(cCPaintedCircle2);
        cCPaintedCircle2.setLayout(cCPaintedCircle2Layout);
        cCPaintedCircle2Layout.setHorizontalGroup(
            cCPaintedCircle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        cCPaintedCircle2Layout.setVerticalGroup(
            cCPaintedCircle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        StatusTextField.setText("jTextField1");

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(CreateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cCPaintedCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCPaintedCircle2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StartDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(StatusTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cCPaintedCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(StatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cCPaintedCircle2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(CreateButton)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // Kullanıcıdan alınan veriler
    String position = PositionTextField.getText().trim();
    String description = DescriptionTextField.getText().trim();
    String startDateStr = StartDateTextField.getText().trim();
    String status = StatusTextField.getText().trim();

    // Giriş doğrulama
    if (position.isEmpty() || description.isEmpty() || startDateStr.isEmpty() || status.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Tarih formatı doğrulama
        LocalDate startDate = LocalDate.parse(startDateStr);

        // JobPosting nesnesi oluşturma
        JobPosting jobPosting = new JobPosting();
        jobPosting.setPositionId(Integer.parseInt(position)); // Pozisyon ID'si numerik olmalı
        jobPosting.setDescription(description);
        jobPosting.setPostingDate(Date.valueOf(startDate));
        jobPosting.setStatus(status);

        // Veritabanına kaydetme
        jobPostingService.addJobPosting(jobPosting);

        // Başarılı mesajı gösterme
        JOptionPane.showMessageDialog(this, "Job posting created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Alanları temizleme
        clearFields();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Position ID must be a number!", "Validation Error", JOptionPane.ERROR_MESSAGE);
    } catch (DateTimeParseException ex) {
        JOptionPane.showMessageDialog(this, "Invalid date format! Use yyyy-MM-dd.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error creating job posting: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField DescriptionTextField;
    private javax.swing.JTextField PositionTextField;
    private javax.swing.JTextField StartDateTextField;
    private javax.swing.JTextField StatusTextField;
    private com.talentbridge.hirewise.custom_components.CCPaintedCircle cCPaintedCircle1;
    private com.talentbridge.hirewise.custom_components.CCPaintedCircle cCPaintedCircle2;
    private com.talentbridge.hirewise.custom_components.CCRoundedButton cCRoundedButton1;
    private com.talentbridge.hirewise.custom_components.CCRoundedButton cCRoundedButton2;
    private com.talentbridge.hirewise.custom_components.CCRoundedButton cCRoundedButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
