package com.talentbridge.hirewise.personnel_system.ui;

import com.talentbridge.hirewise.personnel_system.model.Department;
import com.talentbridge.hirewise.personnel_system.service.DepartmentService;
import java.util.List;

/**
 *
 * @author zahid
 */
public class DepartmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentPanel
     */
    
    
    private final DepartmentService departmentService;
    
    public DepartmentPanel() {
        initComponents();
        departmentService = new DepartmentService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deptNameLabel = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        deptDescLabel = new javax.swing.JLabel();
        departmentDescField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        departmentCombo = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deptNameLabel.setText("Department Name:");
        add(deptNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 115, 29));
        add(departmentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        deptDescLabel.setText("Department Description:");
        add(deptDescLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 29));
        add(departmentDescField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));

        addButton.setText("Add Department");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        refreshButton.setText("Refresh List");
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 120, -1));

        departmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(departmentCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadDepartments() {
    departmentCombo.removeAllItems();
    List<Department> deptList = departmentService.getAllDepartments();
    for (Department d : deptList) {
        departmentCombo.addItem(d.getDepartmentName());
    }
}
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = departmentNameField.getText();
        String desc = departmentDescField.getText();
        departmentService.addDepartment(name, desc);
        loadDepartments();
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> departmentCombo;
    private javax.swing.JTextField departmentDescField;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JLabel deptDescLabel;
    private javax.swing.JLabel deptNameLabel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
